version: "3.8"
services:
  postgres:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5000:5432"
    restart: unless-stopped
